title: Bammon | Precisi贸n y Perfecci贸n
description: Tableros | Backgammon & Ajedrez
theme: jekyll-theme-cayman
permalink: pretty
include: [".htaccess", "404.html"]

# Configuraci贸n para SPA
plugins:
  - jekyll-redirect-from

# Configuraci贸n de build
build:
  output: public